-- World Mood v0.0.2
-- Production-oriented anonymous pulse backend for Supabase.
-- Run this entire file in the Supabase SQL editor.
-- Public users never receive actor hashes. Personal journal notes never leave the device.

create extension if not exists pgcrypto;

create table if not exists public.mood_entries (
  id uuid primary key default gen_random_uuid(),
  mood_score numeric(3,1) not null check (mood_score >= 1 and mood_score <= 10),
  emotion text not null check (emotion in ('great','good','calm','okay','low','stressed','angry','tired')),
  intensity smallint not null check (intensity between 1 and 5),
  reason text null check (reason is null or reason in ('work','family','money','health','love','weather','other')),
  lat_bucket numeric(5,1) null check (lat_bucket is null or lat_bucket between -90 and 90),
  lng_bucket numeric(5,1) null check (lng_bucket is null or lng_bucket between -180 and 180),
  country_code varchar(2) null,
  actor_hash text,
  created_at timestamptz not null default now()
);

alter table public.mood_entries add column if not exists actor_hash text;
alter table public.mood_entries add column if not exists country_code varchar(2);
alter table public.mood_entries drop column if exists note;

-- Existing pre-v0.0.2 rows, if any, get an unrecoverable random actor hash.
update public.mood_entries
set actor_hash = encode(gen_random_bytes(32), 'hex')
where actor_hash is null;

alter table public.mood_entries alter column actor_hash set not null;

create table if not exists public.mood_reactions (
  id bigint generated by default as identity primary key,
  entry_id uuid not null references public.mood_entries(id) on delete cascade,
  actor_hash text not null,
  created_at timestamptz not null default now(),
  unique (entry_id, actor_hash)
);

create index if not exists mood_entries_created_at_idx on public.mood_entries (created_at desc);
create index if not exists mood_entries_geo_idx on public.mood_entries (lat_bucket, lng_bucket)
  where lat_bucket is not null and lng_bucket is not null;
create index if not exists mood_entries_actor_idx on public.mood_entries (actor_hash, created_at desc);
create index if not exists mood_reactions_entry_idx on public.mood_reactions (entry_id);

alter table public.mood_entries enable row level security;
alter table public.mood_reactions enable row level security;

-- Do not expose the base tables directly to anonymous clients.
revoke all on public.mood_entries from anon;
revoke all on public.mood_reactions from anon;

-- Remove policies from earlier versions. Access now happens only through safe RPC functions.
drop policy if exists "public can read recent moods" on public.mood_entries;
drop policy if exists "public can submit valid moods" on public.mood_entries;

create or replace function public.submit_mood(
  p_mood_score numeric,
  p_emotion text,
  p_intensity integer,
  p_reason text default null,
  p_lat_bucket numeric default null,
  p_lng_bucket numeric default null,
  p_country_code text default null,
  p_actor_hash text default null
)
returns table(id uuid, created_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_created timestamptz;
begin
  if p_actor_hash is null or p_actor_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'INVALID_ACTOR';
  end if;

  if p_mood_score < 1 or p_mood_score > 10 then raise exception 'INVALID_SCORE'; end if;
  if p_emotion not in ('great','good','calm','okay','low','stressed','angry','tired') then raise exception 'INVALID_EMOTION'; end if;
  if p_intensity < 1 or p_intensity > 5 then raise exception 'INVALID_INTENSITY'; end if;
  if p_reason is not null and p_reason not in ('work','family','money','health','love','weather','other') then raise exception 'INVALID_REASON'; end if;
  if p_lat_bucket is not null and (p_lat_bucket < -90 or p_lat_bucket > 90 or mod(p_lat_bucket * 2, 1) <> 0) then raise exception 'INVALID_LAT'; end if;
  if p_lng_bucket is not null and (p_lng_bucket < -180 or p_lng_bucket > 180 or mod(p_lng_bucket * 2, 1) <> 0) then raise exception 'INVALID_LNG'; end if;
  if p_country_code is not null and p_country_code !~ '^[A-Za-z]{2}$' then raise exception 'INVALID_COUNTRY'; end if;

  if exists (
    select 1
    from public.mood_entries m
    where m.actor_hash = p_actor_hash
      and m.created_at > now() - interval '45 seconds'
  ) then
    raise exception 'RATE_LIMIT';
  end if;

  insert into public.mood_entries (
    mood_score, emotion, intensity, reason, lat_bucket, lng_bucket, country_code, actor_hash
  ) values (
    round(p_mood_score, 1), p_emotion, p_intensity, p_reason,
    p_lat_bucket, p_lng_bucket, upper(p_country_code), p_actor_hash
  )
  returning mood_entries.id, mood_entries.created_at into v_id, v_created;

  return query select v_id, v_created;
end;
$$;

create or replace function public.get_live_moods(
  p_since timestamptz default now() - interval '24 hours',
  p_limit integer default 3000
)
returns table(
  id uuid,
  mood_score numeric,
  emotion text,
  intensity smallint,
  reason text,
  lat_bucket numeric,
  lng_bucket numeric,
  country_code varchar,
  created_at timestamptz,
  resonance_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    m.id,
    m.mood_score,
    m.emotion,
    m.intensity,
    m.reason,
    m.lat_bucket,
    m.lng_bucket,
    m.country_code,
    m.created_at,
    (select count(*) from public.mood_reactions r where r.entry_id = m.id) as resonance_count
  from public.mood_entries m
  where m.created_at >= greatest(p_since, now() - interval '90 days')
  order by m.created_at desc
  limit least(greatest(coalesce(p_limit, 3000), 1), 5000);
$$;

create or replace function public.react_to_mood(
  p_entry_id uuid,
  p_actor_hash text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count bigint;
begin
  if p_actor_hash is null or p_actor_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'INVALID_ACTOR';
  end if;

  if not exists (
    select 1 from public.mood_entries
    where id = p_entry_id
      and created_at > now() - interval '30 days'
  ) then
    raise exception 'ENTRY_NOT_FOUND';
  end if;

  insert into public.mood_reactions(entry_id, actor_hash)
  values (p_entry_id, p_actor_hash)
  on conflict (entry_id, actor_hash) do nothing;

  select count(*) into v_count from public.mood_reactions where entry_id = p_entry_id;
  return v_count;
end;
$$;

grant execute on function public.submit_mood(numeric, text, integer, text, numeric, numeric, text, text) to anon;
grant execute on function public.get_live_moods(timestamptz, integer) to anon;
grant execute on function public.react_to_mood(uuid, text) to anon;

-- Optional server-side retention cleanup, suitable for a scheduled Supabase job:
-- delete from public.mood_reactions where entry_id in (select id from public.mood_entries where created_at < now() - interval '90 days');
-- delete from public.mood_entries where created_at < now() - interval '90 days';

-- Defense in depth for direct Data API access.
revoke execute on function public.submit_mood(numeric, text, integer, text, numeric, numeric, text, text) from public, authenticated;
revoke execute on function public.get_live_moods(timestamptz, integer) from public, authenticated;
revoke execute on function public.react_to_mood(uuid, text) from public, authenticated;

grant execute on function public.submit_mood(numeric, text, integer, text, numeric, numeric, text, text) to anon;
grant execute on function public.get_live_moods(timestamptz, integer) to anon;
grant execute on function public.react_to_mood(uuid, text) to anon;

drop policy if exists "deny direct mood entry access" on public.mood_entries;
create policy "deny direct mood entry access" on public.mood_entries
as restrictive for all to anon, authenticated
using (false) with check (false);

drop policy if exists "deny direct reaction access" on public.mood_reactions;
create policy "deny direct reaction access" on public.mood_reactions
as restrictive for all to anon, authenticated
using (false) with check (false);
