-- Moodaro v0.0.4 additive social upgrade.
-- Backward compatible: the v0.0.3 RPCs remain unchanged.

alter table public.mood_entries add column if not exists public_message text;
alter table public.mood_entries add column if not exists context_tag text;
alter table public.mood_entries add column if not exists event_slug text;

create table if not exists public.mood_reports (
  id bigint generated by default as identity primary key,
  entry_id uuid not null references public.mood_entries(id) on delete cascade,
  actor_hash text not null,
  reason text not null default 'community',
  created_at timestamptz not null default now(),
  unique(entry_id, actor_hash)
);

create table if not exists public.world_questions (
  id uuid primary key default gen_random_uuid(),
  question text not null,
  options jsonb not null,
  active_from timestamptz not null default now(),
  active_until timestamptz not null default (now() + interval '30 days'),
  created_at timestamptz not null default now(),
  check (jsonb_typeof(options) = 'array')
);

create table if not exists public.world_question_votes (
  question_id uuid not null references public.world_questions(id) on delete cascade,
  actor_hash text not null,
  choice smallint not null,
  updated_at timestamptz not null default now(),
  primary key(question_id, actor_hash)
);

create table if not exists public.mood_events (
  slug text primary key,
  title text not null,
  emoji text not null default '✨',
  active_from timestamptz not null,
  active_until timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.mood_circles (
  id uuid primary key default gen_random_uuid(),
  code varchar(8) not null unique,
  creator_hash text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days')
);

create table if not exists public.mood_circle_entries (
  id bigint generated by default as identity primary key,
  circle_id uuid not null references public.mood_circles(id) on delete cascade,
  actor_hash text not null,
  mood_score numeric(3,1) not null check (mood_score between 1 and 10),
  emotion text not null check (emotion in ('great','good','calm','okay','low','stressed','angry','tired')),
  created_at timestamptz not null default now()
);

create index if not exists mood_reports_entry_idx on public.mood_reports(entry_id);
create index if not exists world_question_votes_question_idx on public.world_question_votes(question_id);
create index if not exists mood_circle_entries_circle_idx on public.mood_circle_entries(circle_id, created_at desc);
create index if not exists mood_circle_entries_actor_idx on public.mood_circle_entries(actor_hash, created_at desc);
create index if not exists mood_entries_context_idx on public.mood_entries(context_tag, created_at desc) where context_tag is not null;
create index if not exists mood_entries_event_idx on public.mood_entries(event_slug, created_at desc) where event_slug is not null;

alter table public.mood_reports enable row level security;
alter table public.world_questions enable row level security;
alter table public.world_question_votes enable row level security;
alter table public.mood_events enable row level security;
alter table public.mood_circles enable row level security;
alter table public.mood_circle_entries enable row level security;

revoke all on public.mood_reports from anon, authenticated;
revoke all on public.world_questions from anon, authenticated;
revoke all on public.world_question_votes from anon, authenticated;
revoke all on public.mood_events from anon, authenticated;
revoke all on public.mood_circles from anon, authenticated;
revoke all on public.mood_circle_entries from anon, authenticated;

create or replace function public.submit_mood_v2(
  p_mood_score numeric,
  p_emotion text,
  p_intensity integer,
  p_reason text default null,
  p_lat_bucket numeric default null,
  p_lng_bucket numeric default null,
  p_country_code text default null,
  p_actor_hash text default null,
  p_public_message text default null,
  p_context_tag text default null,
  p_event_slug text default null
)
returns table(id uuid, created_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_created timestamptz;
  v_message text;
begin
  v_message := nullif(trim(regexp_replace(coalesce(p_public_message, ''), '[[:space:]]+', ' ', 'g')), '');
  if v_message is not null and char_length(v_message) > 120 then raise exception 'MESSAGE_TOO_LONG'; end if;
  if v_message is not null and v_message ~* '(https?://|www\.|[[:alnum:]._%+-]+@[[:alnum:].-]+\.[[:alpha:]]{2,})' then raise exception 'MESSAGE_LINKS_NOT_ALLOWED'; end if;

  if p_context_tag is not null and p_context_tag not in ('monday','exam_week','travel_day','game_night','new_parents','workday') then
    raise exception 'INVALID_CONTEXT';
  end if;

  if p_event_slug is not null and not exists (
    select 1 from public.mood_events e
    where e.slug = p_event_slug and now() between e.active_from and e.active_until
  ) then
    raise exception 'INVALID_EVENT';
  end if;

  select s.id, s.created_at into v_id, v_created
  from public.submit_mood(
    p_mood_score, p_emotion, p_intensity, p_reason,
    p_lat_bucket, p_lng_bucket, p_country_code, p_actor_hash
  ) s;

  update public.mood_entries m
  set public_message = v_message,
      context_tag = p_context_tag,
      event_slug = p_event_slug
  where m.id = v_id;

  return query select v_id, v_created;
end;
$$;

create or replace function public.get_live_moods_v2(
  p_since timestamptz default now() - interval '24 hours',
  p_limit integer default 3000
)
returns table(
  id uuid,
  mood_score numeric,
  emotion text,
  intensity smallint,
  reason text,
  public_message text,
  context_tag text,
  event_slug text,
  lat_bucket numeric,
  lng_bucket numeric,
  country_code varchar,
  created_at timestamptz,
  resonance_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    m.id, m.mood_score, m.emotion, m.intensity, m.reason,
    m.public_message, m.context_tag, m.event_slug,
    m.lat_bucket, m.lng_bucket, m.country_code, m.created_at,
    (select count(*) from public.mood_reactions r where r.entry_id = m.id) as resonance_count
  from public.mood_entries m
  where m.created_at >= greatest(p_since, now() - interval '90 days')
    and (select count(*) from public.mood_reports mr where mr.entry_id = m.id) < 3
  order by m.created_at desc
  limit least(greatest(coalesce(p_limit, 3000), 1), 5000);
$$;

create or replace function public.report_mood(
  p_entry_id uuid,
  p_actor_hash text,
  p_reason text default 'community'
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_actor_hash is null or p_actor_hash !~ '^[0-9a-f]{64}$' then raise exception 'INVALID_ACTOR'; end if;
  if not exists (select 1 from public.mood_entries m where m.id = p_entry_id) then return false; end if;
  insert into public.mood_reports(entry_id, actor_hash, reason)
  values (p_entry_id, p_actor_hash, left(coalesce(p_reason, 'community'), 40))
  on conflict (entry_id, actor_hash) do nothing;
  return true;
end;
$$;

create or replace function public.get_active_world_question()
returns table(id uuid, question text, options jsonb, counts jsonb, total bigint)
language sql
stable
security definer
set search_path = public
as $$
  select q.id, q.question, q.options,
    coalesce((
      select jsonb_agg(x.vote_count order by x.choice)
      from (
        select gs as choice, count(v.actor_hash)::int as vote_count
        from generate_series(0, jsonb_array_length(q.options) - 1) gs
        left join public.world_question_votes v on v.question_id = q.id and v.choice = gs
        group by gs
      ) x
    ), '[]'::jsonb) as counts,
    (select count(*) from public.world_question_votes v where v.question_id = q.id) as total
  from public.world_questions q
  where now() between q.active_from and q.active_until
  order by q.active_from desc
  limit 1;
$$;

create or replace function public.vote_world_question(
  p_question_id uuid,
  p_choice integer,
  p_actor_hash text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_options integer;
  v_total bigint;
begin
  if p_actor_hash is null or p_actor_hash !~ '^[0-9a-f]{64}$' then raise exception 'INVALID_ACTOR'; end if;
  select jsonb_array_length(q.options) into v_options
  from public.world_questions q
  where q.id = p_question_id and now() between q.active_from and q.active_until;
  if v_options is null then raise exception 'QUESTION_NOT_ACTIVE'; end if;
  if p_choice < 0 or p_choice >= v_options then raise exception 'INVALID_CHOICE'; end if;

  insert into public.world_question_votes(question_id, actor_hash, choice, updated_at)
  values (p_question_id, p_actor_hash, p_choice, now())
  on conflict (question_id, actor_hash)
  do update set choice = excluded.choice, updated_at = now();

  select count(*) into v_total from public.world_question_votes where question_id = p_question_id;
  return v_total;
end;
$$;

create or replace function public.get_active_mood_events()
returns table(slug text, title text, emoji text, starts_at timestamptz, ends_at timestamptz, checkins bigint, average_score numeric)
language sql
stable
security definer
set search_path = public
as $$
  select e.slug, e.title, e.emoji, e.active_from, e.active_until,
    count(m.id) as checkins,
    round(avg(m.mood_score), 1) as average_score
  from public.mood_events e
  left join public.mood_entries m on m.event_slug = e.slug and m.created_at between e.active_from and e.active_until
  where now() between e.active_from and e.active_until
  group by e.slug, e.title, e.emoji, e.active_from, e.active_until
  order by e.active_until asc;
$$;

create or replace function public.create_mood_circle(p_actor_hash text)
returns table(code varchar, members bigint, checkins bigint, score numeric, emotion text, latest_at timestamptz, expires_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_code varchar(8);
  v_expires timestamptz;
begin
  if p_actor_hash is null or p_actor_hash !~ '^[0-9a-f]{64}$' then raise exception 'INVALID_ACTOR'; end if;
  loop
    v_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
    insert into public.mood_circles(code, creator_hash)
    values (v_code, p_actor_hash)
    on conflict do nothing
    returning id, mood_circles.expires_at into v_id, v_expires;
    exit when v_id is not null;
  end loop;
  return query select v_code, 0::bigint, 0::bigint, null::numeric, null::text, null::timestamptz, v_expires;
end;
$$;

create or replace function public.submit_circle_mood(
  p_code text,
  p_emotion text,
  p_mood_score numeric,
  p_actor_hash text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_circle uuid;
begin
  if p_actor_hash is null or p_actor_hash !~ '^[0-9a-f]{64}$' then raise exception 'INVALID_ACTOR'; end if;
  if p_emotion not in ('great','good','calm','okay','low','stressed','angry','tired') then raise exception 'INVALID_EMOTION'; end if;
  if p_mood_score < 1 or p_mood_score > 10 then raise exception 'INVALID_SCORE'; end if;
  select c.id into v_circle from public.mood_circles c where c.code = upper(p_code) and c.expires_at > now();
  if v_circle is null then raise exception 'CIRCLE_NOT_FOUND'; end if;
  if exists (
    select 1 from public.mood_circle_entries ce
    where ce.circle_id = v_circle and ce.actor_hash = p_actor_hash and ce.created_at > now() - interval '45 seconds'
  ) then raise exception 'RATE_LIMIT'; end if;
  insert into public.mood_circle_entries(circle_id, actor_hash, mood_score, emotion)
  values (v_circle, p_actor_hash, round(p_mood_score,1), p_emotion);
  return true;
end;
$$;

create or replace function public.get_circle_summary(p_code text)
returns table(code varchar, members bigint, checkins bigint, score numeric, emotion text, latest_at timestamptz, expires_at timestamptz)
language sql
stable
security definer
set search_path = public
as $$
  select c.code,
    count(distinct ce.actor_hash) as members,
    count(ce.id) as checkins,
    round(avg(ce.mood_score), 1) as score,
    (
      select ce2.emotion
      from public.mood_circle_entries ce2
      where ce2.circle_id = c.id and ce2.created_at > now() - interval '24 hours'
      group by ce2.emotion
      order by count(*) desc, ce2.emotion
      limit 1
    ) as emotion,
    max(ce.created_at) as latest_at,
    c.expires_at
  from public.mood_circles c
  left join public.mood_circle_entries ce on ce.circle_id = c.id and ce.created_at > now() - interval '24 hours'
  where c.code = upper(p_code) and c.expires_at > now()
  group by c.id, c.code, c.expires_at;
$$;

insert into public.world_questions(id, question, options, active_from, active_until)
values (
  '00000000-0000-4000-8000-000000000401'::uuid,
  'How hopeful do you feel about the next seven days?',
  '["Not very","A little","Mixed","Hopeful","Very hopeful"]'::jsonb,
  '2026-09-01T00:00:00Z'::timestamptz,
  '2030-01-01T00:00:00Z'::timestamptz
)
on conflict (id) do update set
  question = excluded.question,
  options = excluded.options,
  active_from = excluded.active_from,
  active_until = excluded.active_until;

revoke execute on function public.submit_mood_v2(numeric,text,integer,text,numeric,numeric,text,text,text,text,text) from public, authenticated;
revoke execute on function public.get_live_moods_v2(timestamptz,integer) from public, authenticated;
revoke execute on function public.report_mood(uuid,text,text) from public, authenticated;
revoke execute on function public.get_active_world_question() from public, authenticated;
revoke execute on function public.vote_world_question(uuid,integer,text) from public, authenticated;
revoke execute on function public.get_active_mood_events() from public, authenticated;
revoke execute on function public.create_mood_circle(text) from public, authenticated;
revoke execute on function public.submit_circle_mood(text,text,numeric,text) from public, authenticated;
revoke execute on function public.get_circle_summary(text) from public, authenticated;

grant execute on function public.submit_mood_v2(numeric,text,integer,text,numeric,numeric,text,text,text,text,text) to anon;
grant execute on function public.get_live_moods_v2(timestamptz,integer) to anon;
grant execute on function public.report_mood(uuid,text,text) to anon;
grant execute on function public.get_active_world_question() to anon;
grant execute on function public.vote_world_question(uuid,integer,text) to anon;
grant execute on function public.get_active_mood_events() to anon;
grant execute on function public.create_mood_circle(text) to anon;
grant execute on function public.submit_circle_mood(text,text,numeric,text) to anon;
grant execute on function public.get_circle_summary(text) to anon;

drop policy if exists "deny reports direct access" on public.mood_reports;
create policy "deny reports direct access" on public.mood_reports as restrictive for all to anon, authenticated using (false) with check (false);
drop policy if exists "deny questions direct access" on public.world_questions;
create policy "deny questions direct access" on public.world_questions as restrictive for all to anon, authenticated using (false) with check (false);
drop policy if exists "deny question votes direct access" on public.world_question_votes;
create policy "deny question votes direct access" on public.world_question_votes as restrictive for all to anon, authenticated using (false) with check (false);
drop policy if exists "deny events direct access" on public.mood_events;
create policy "deny events direct access" on public.mood_events as restrictive for all to anon, authenticated using (false) with check (false);
drop policy if exists "deny circles direct access" on public.mood_circles;
create policy "deny circles direct access" on public.mood_circles as restrictive for all to anon, authenticated using (false) with check (false);
drop policy if exists "deny circle entries direct access" on public.mood_circle_entries;
create policy "deny circle entries direct access" on public.mood_circle_entries as restrictive for all to anon, authenticated using (false) with check (false);
